flappybirdv0:
  env_id : FlappyBird-v0
  epsilon_init : 1
  epsilon_min : 0.05
  epsilon_dacay : 0.9995
  replay_memory_size : 100000
  min_batch_size : 32
  network_sync_rate : 0.001
  alpha : 0.001
  gamma : 0.99
  reward_threshold : 100000